# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/grads/p/prateek_24prasad/ml_new/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/grads/p/prateek_24prasad/ml_new/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  /home/grads/p/prateek_24prasad/ml_new/src/ufixed_buffer.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/ufixed_shift_registers.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/mac.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/conv_controller.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/sfixed_fifo.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/tan_h.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/convolution.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/average_pooler.vhd
  /home/grads/p/prateek_24prasad/ml_new/src/convolution_layer.vhd
  /home/grads/p/prateek_24prasad/ml_new/tb/conv_layer_tb_wo_sig.vhd
}
synth_design -top conv_layer_tb_wo_sig -part xc7vx485tffg1157-1
write_checkpoint -noxdef conv_layer_tb_wo_sig.dcp
catch { report_utilization -file conv_layer_tb_wo_sig_utilization_synth.rpt -pb conv_layer_tb_wo_sig_utilization_synth.pb }
